In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [3]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([3,2])
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [4]:
# SHuffling

not_shuffled = tf.constant([[3,2],
                           [5,6],
                           [9,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 6],
       [9, 5]])>

In [5]:
tf.random.set_seed(-42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [9, 5],
       [5, 6]])>

In [6]:
import numpy as np
numpy_a = np.arange(1,25)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
tf.constant(numpy_a, shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [8]:
##Getting information from data
# rank/dim
# shape
# size
# dtype

In [9]:
# Creating a rank 4 tensor

rank4 = tf.ones(shape=(2,4,3,4))
rank4

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [10]:
rank4[:2,:2,:2,2:]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [11]:
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [12]:
rank2_tensor = tf.constant([[7,3],
                            [5,4]])

In [13]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 3],
       [5, 4]])>

In [14]:
rank2_tensor.ndim 

2

INDEXING 


In [15]:
rank2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [16]:
# last item
rank2_tensor[:-1,:-1]

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[7]])>

ADDING AN EXTRA DIMENSION

In [17]:
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[7],
        [3]],

       [[5],
        [4]]])>

In [18]:
rank3_tensor = tf.expand_dims(rank2_tensor, axis=0)
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [19]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [20]:
# Manipulations
tensor_uniform = tf.random.uniform(shape=(3,5),minval=5.0,maxval=5.9)

In [21]:
tensor_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[5.3739567, 5.85714  , 5.7719216, 5.7314014, 5.084743 ],
       [5.231156 , 5.5555124, 5.836748 , 5.8652124, 5.561718 ],
       [5.282711 , 5.3492794, 5.8134127, 5.5981326, 5.156321 ]],
      dtype=float32)>

**Matrix multiplcation**
1. In matrix multiplicaion the inner matrix must be the same 
2. The number of columns and row in the results must be the outer size

In [22]:
tf.matmul(rank2_tensor,rank2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [23]:
rank2_tensor @ rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [24]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [25]:
A1 = tf.constant([[3,5],
                 [7,6],
                 [9,8]], dtype=tf.float32)
A2 = tf.constant([[1,2],
                 [3,6],
                 [7,8]], dtype=tf.float32)

A1,A2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 6.],
        [7., 8.]], dtype=float32)>)

In [26]:
tf.multiply(A1,A2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3., 10.],
       [21., 36.],
       [63., 64.]], dtype=float32)>

In [27]:
tf.reshape(A2, shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [6., 7., 8.]], dtype=float32)>

In [28]:
tf.matmul(A1, tf.reshape(A2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [29]:
A1 @ tf.reshape(A2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [30]:
# A1,A2
A1, tf.transpose(A2)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 3., 7.],
        [2., 6., 8.]], dtype=float32)>)

**The dot Product**
* `tf.matmul`
*  `tf.tensordot()`

In [31]:
A1,A2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 6.],
        [7., 8.]], dtype=float32)>)

In [32]:
tf.tensordot(tf.transpose(A1), A2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 87., 120.],
       [ 79., 110.]], dtype=float32)>

In [33]:
tf.matmul(A1, tf.transpose(A2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 13.,  39.,  61.],
       [ 19.,  57.,  97.],
       [ 25.,  75., 127.]], dtype=float32)>

In [34]:
tf.tensordot(A1, tf.transpose(A2),axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 13.,  39.,  61.],
       [ 19.,  57.,  97.],
       [ 25.,  75., 127.]], dtype=float32)>

In [35]:
tf.matmul(A1, tf.reshape(A2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [36]:
print(A1.shape, tf.transpose(A2).shape)

(3, 2) (2, 3)


In [37]:
B = tf.constant([7,5])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5])>

In [38]:
c = tf.cast(B, dtype='int16')
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([7, 5], dtype=int16)>

**Aggregations in tensor**

In [39]:
# fing the max
A1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 5.],
       [7., 6.],
       [9., 8.]], dtype=float32)>

In [40]:
print(tf.reduce_max(A1))
print(tf.reduce_sum(A2))
# print(tf.reduce_median(A1))

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(27.0, shape=(), dtype=float32)


In [41]:
tf.math.reduce_std(A1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.9720266>

In [42]:
tf.math.reduce_variance(A1)

<tf.Tensor: shape=(), dtype=float32, numpy=3.888889>

**Postional mix and min**

In [45]:
C = tf.random.uniform(shape=([50]))
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7240648 , 0.77869725, 0.05407071, 0.18458593, 0.65802383,
       0.3962593 , 0.25334418, 0.65403306, 0.6395272 , 0.08288562,
       0.803555  , 0.0489229 , 0.9910549 , 0.59677076, 0.27476215,
       0.01587689, 0.8411596 , 0.7738614 , 0.22665286, 0.5007031 ,
       0.71522224, 0.6452006 , 0.24328065, 0.6434914 , 0.07877457,
       0.8125453 , 0.8521453 , 0.4619068 , 0.56628263, 0.29240835,
       0.3256327 , 0.02067995, 0.77554905, 0.40309536, 0.8725091 ,
       0.36907542, 0.8130264 , 0.67354536, 0.05214679, 0.5410476 ,
       0.69708097, 0.28457904, 0.6262944 , 0.31551635, 0.6209048 ,
       0.1984936 , 0.5539496 , 0.13383365, 0.2829317 , 0.2171135 ],
      dtype=float32)>

In [46]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [47]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9910549>

In [48]:
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [49]:
C[tf.argmin(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.01587689>

One-hot encoding

In [54]:
some_no = [4,3,2,1]
some_no

[4, 3, 2, 1]

In [56]:
tf.one_hot(some_no,depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [58]:
D = tf.range(1,11)
D

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [59]:
tf.square(D)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])>

In [61]:
tf.sqrt(tf.cast(D, dtype='float32'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777], dtype=float32)>

In [64]:
tf.math.log(tf.cast(D, dtype='float32'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851], dtype=float32)>

In [66]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]