In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [4]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([3,2])
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [5]:
# SHuffling

not_shuffled = tf.constant([[3,2],
                           [5,6],
                           [9,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 6],
       [9, 5]])>

In [6]:
tf.random.set_seed(-42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [9, 5],
       [5, 6]])>

In [7]:
import numpy as np
numpy_a = np.arange(1,25)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
tf.constant(numpy_a, shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [9]:
##Getting information from data
# rank/dim
# shape
# size
# dtype

In [10]:
# Creating a rank 4 tensor

rank4 = tf.ones(shape=(2,4,3,4))
rank4

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [11]:
rank4[:2,:2,:2,2:]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [12]:
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [13]:
rank2_tensor = tf.constant([[7,3],
                            [5,4]])

In [14]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 3],
       [5, 4]])>

In [15]:
rank2_tensor.ndim 

2

INDEXING 


In [16]:
rank2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [17]:
# last item
rank2_tensor[:-1,:-1]

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[7]])>

ADDING AN EXTRA DIMENSION

In [18]:
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[7],
        [3]],

       [[5],
        [4]]])>

In [19]:
rank3_tensor = tf.expand_dims(rank2_tensor, axis=0)
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [20]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [21]:
# Manipulations
tensor_uniform = tf.random.uniform(shape=(3,5),minval=5.0,maxval=5.9)

In [22]:
tensor_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[5.3739567, 5.85714  , 5.7719216, 5.7314014, 5.084743 ],
       [5.231156 , 5.5555124, 5.836748 , 5.8652124, 5.561718 ],
       [5.282711 , 5.3492794, 5.8134127, 5.5981326, 5.156321 ]],
      dtype=float32)>

Matrix multiplcation

In [23]:
tf.matmul(rank2_tensor,rank2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [24]:
rank2_tensor @ rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [25]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [35]:
A1 = tf.constant([[3,5],
                 [7,6],
                 [9,8]], dtype=tf.float32)
A2 = tf.constant([[1,2],
                 [3,6],
                 [7,8]], dtype=tf.float32)

tf.multiply(A1, A2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3., 10.],
       [21., 36.],
       [63., 64.]], dtype=float32)>