In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [4]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([3,2])
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [5]:
# SHuffling

not_shuffled = tf.constant([[3,2],
                           [5,6],
                           [9,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 6],
       [9, 5]])>

In [6]:
tf.random.set_seed(-42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [9, 5],
       [5, 6]])>

In [7]:
import numpy as np
numpy_a = np.arange(1,25)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
tf.constant(numpy_a, shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [9]:
##Getting information from data
# rank/dim
# shape
# size
# dtype

In [10]:
# Creating a rank 4 tensor

rank4 = tf.ones(shape=(2,4,3,4))
rank4

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [11]:
rank4[:2,:2,:2,2:]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [12]:
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [13]:
rank2_tensor = tf.constant([[7,3],
                            [5,4]])

In [14]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 3],
       [5, 4]])>

In [15]:
rank2_tensor.ndim 

2

INDEXING 


In [16]:
rank2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [17]:
# last item
rank2_tensor[:-1,:-1]

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[7]])>

ADDING AN EXTRA DIMENSION

In [18]:
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[7],
        [3]],

       [[5],
        [4]]])>

In [19]:
rank3_tensor = tf.expand_dims(rank2_tensor, axis=0)
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [20]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [21]:
# Manipulations
tensor_uniform = tf.random.uniform(shape=(3,5),minval=5.0,maxval=5.9)

In [22]:
tensor_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[5.3739567, 5.85714  , 5.7719216, 5.7314014, 5.084743 ],
       [5.231156 , 5.5555124, 5.836748 , 5.8652124, 5.561718 ],
       [5.282711 , 5.3492794, 5.8134127, 5.5981326, 5.156321 ]],
      dtype=float32)>

**Matrix multiplcation**
1. In matrix multiplicaion the inner matrix must be the same 
2. The number of columns and row in the results must be the outer size

In [23]:
tf.matmul(rank2_tensor,rank2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [24]:
rank2_tensor @ rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 33],
       [55, 31]])>

In [25]:
rank3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[7, 3],
        [5, 4]]])>

In [36]:
A1 = tf.constant([[3,5],
                 [7,6],
                 [9,8]], dtype=tf.float32)
A2 = tf.constant([[1,2],
                 [3,6],
                 [7,8]], dtype=tf.float32)

A1,A2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 6.],
        [7., 8.]], dtype=float32)>)

In [45]:
tf.multiply(A1,A2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3., 10.],
       [21., 36.],
       [63., 64.]], dtype=float32)>

In [40]:
tf.reshape(A2, shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [6., 7., 8.]], dtype=float32)>

In [43]:
tf.matmul(A1, tf.reshape(A2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [46]:
A1 @ tf.reshape(A2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [50]:
# A1,A2
A1, tf.transpose(A2)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 3., 7.],
        [2., 6., 8.]], dtype=float32)>)

**The dot Product**
* `tf.matmul`
*  `tf.tensordot()`

In [55]:
A1,A2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 5.],
        [7., 6.],
        [9., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 6.],
        [7., 8.]], dtype=float32)>)

In [58]:
tf.tensordot(tf.transpose(A1), A2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 87., 120.],
       [ 79., 110.]], dtype=float32)>

In [61]:
tf.matmul(A1, tf.transpose(A2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 13.,  39.,  61.],
       [ 19.,  57.,  97.],
       [ 25.,  75., 127.]], dtype=float32)>

In [59]:
tf.tensordot(A1, tf.transpose(A2),axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 13.,  39.,  61.],
       [ 19.,  57.,  97.],
       [ 25.,  75., 127.]], dtype=float32)>

In [63]:
tf.matmul(A1, tf.reshape(A2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[33., 41., 49.],
       [43., 56., 69.],
       [57., 74., 91.]], dtype=float32)>

In [64]:
print(A1.shape, tf.transpose(A2).shape)

(3, 2) (2, 3)


In [65]:
B = tf.constant([7,5])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5])>

In [66]:
c = tf.cast(B, dtype='int16')
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([7, 5], dtype=int16)>

**Aggregations in tensor**

In [67]:
# fing the max
A1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 5.],
       [7., 6.],
       [9., 8.]], dtype=float32)>

In [76]:
print(tf.reduce_max(A1))
print(tf.reduce_sum(A2))
# print(tf.reduce_median(A1))

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(27.0, shape=(), dtype=float32)


In [84]:
tf.math.reduce_std(A1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.9720266>

In [86]:
tf.math.reduce_variance(A1)

<tf.Tensor: shape=(), dtype=float32, numpy=3.888889>